# Generated by Django 4.1.4 on 2022-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=200)),
                ("purchase_link", models.URLField(max_length=500)),
            ],
        ),
    ]
