# Generated by Django 4.1.4 on 2022-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="book", name="genre",),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(related_name="books", to="home.genre"),
        ),
    ]
