# Generated by Django 4.1.4 on 2022-12-10 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
