# Generated by Django 4.1.4 on 2022-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_comment_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="user",),
    ]
