# Generated by Django 4.1.4 on 2022-12-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_comment_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_posted",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
